### ISSUE TITLE
Carla environment for evaluation

### ISSUE THREAD

**Issue by scok30** [OpenDriveLab/TCP#30]
hello! first thank you for releasing this codebase. though it might be a silly problem, but i want to ask the environment that you setup the carla program: in a linux server or a computer with desktop system? because i was trying to build carla in our online server, but found that it requires to reboot the computer. we can't reboot it for installing this environment.

**Comment by WPH-commit** [comment]
Hi, do you set up the pre-built Carla as instructed in the setup section? In our case, we do not need to reboot the computer.
