### ISSUE TITLE
val dataset

### ISSUE THREAD

**Issue by a1wj1** [OpenDriveLab/TCP#38]
When submitting the leaderboard, the training dataset was for 8 towns. What is the val dataset?

**Comment by WPH-commit** [comment]
The CARLA leaderboard uses some secret routes for evaluation.

**Comment by a1wj1** [comment]
Hello, what I mean is the dataset during training, as shown in the figure.

![Uploading 1688634467428.png…]()

**Comment by WPH-commit** [comment]
The val dataset is still the same. So the training data and validation data may belong to the same town but different routes.

**Comment by a1wj1** [comment]
感谢，明白了
