### ISSUE TITLE
code

### ISSUE THREAD

**Issue by a1wj1** [OpenDriveLab/TCP#39]
This code doesn't match the formulas in the paper. Could you please help explain,?

![1688634587122](https://github.com/OpenDriveLab/TCP/assets/38905689/d4e42bf2-896c-4f00-acac-8f42bb8585b4)
![1688634659207](https://github.com/OpenDriveLab/TCP/assets/38905689/702520d6-64e7-4a2f-bbac-895e166044c5)
![1688634675450](https://github.com/OpenDriveLab/TCP/assets/38905689/0ea2721e-29c3-42e5-a905-b2491a1ef929)

**Comment by a1wj1** [comment]
In j_ctrl = self.join_ctrl(torch.cat([feature_emb, measurement_feature], 1))，why not h_ctl but measurement_feature

**Comment by WPH-commit** [comment]
This is the initial step so the measurement feature is used instead of h_ctrl.
![image](https://github.com/OpenDriveLab/TCP/assets/62696862/36e36a2d-75c0-4b8e-8d5c-510ee5ff3982)
