### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by a1wj1** [OpenDriveLab/TCP#41]
![1688870451493](https://github.com/OpenDriveLab/TCP/assets/38905689/ef75d3e2-7786-4ddb-ac56-ab52c7b9f03a)

I haven't understood the code for generating the action yet. Could you please explain it? Thank you

**Comment by WPH-commit** [comment]
Hi, the code just calculates the mode of the Beta distribution specified by the alpha and beta values. And it then converts the value between 0~1 to -1~1.
