### ISSUE TITLE
data collection

### ISSUE THREAD

**Issue by a1wj1** [OpenDriveLab/TCP#44]
Hi，when I run the approach_ The agent collected data and reported this error：

AttributeError: 'NoneType' object has no attribute 'get_location'
leaderboard.autoagents.agent_wrapper.AgentError: 'NoneType' object has no attribute 'get_location'

Why?

**Comment by WPH-commit** [comment]
It seems that there exist errors during agent setup. There should some true error messages before this. Could you please provide more information about that?
