### ISSUE TITLE
the time limit for agent blocking

### ISSUE THREAD

**Issue by a1wj1** [OpenDriveLab/TCP#46]
May I ask where the time limit for agent blocking  is configured in the code?

**Comment by WPH-commit** [comment]
https://github.com/OpenDriveLab/TCP/blob/3947ec4e06b05f19b1d964a4281c7c4c1539f1bb/leaderboard/leaderboard/scenarios/route_scenario.py#L579
You can modify the `below_threshold_max_time`.

**Comment by a1wj1** [comment]
Thank you!
