### ISSUE TITLE
failure example

### ISSUE THREAD

**Issue by a1wj1** [OpenDriveLab/TCP#47]
May I ask which route and scenario file test results are shown in the image of this failure example

![1690200754715](https://github.com/OpenDriveLab/TCP/assets/38905689/753fc0a9-7d21-412e-8340-4c375f7f6d52)

**Comment by WPH-commit** [comment]
I do not remember the exact routes of them, but they should come from the Town05-long and Town02-long routes in the [Transfuser](https://github.com/autonomousvision/transfuser/tree/cvpr2021/leaderboard/data) repo.
