### ISSUE TITLE
Confirmation on Dataset

### ISSUE THREAD

**Issue by DeviRajendra** [OpenDriveLab/TCP#52]
Hello,

I am inquiring to confirm whether the dataset available on the provided Google Drive link was used for training the model that achieved the top position on the CARLA leaderboard. This verification is crucial for understanding the dataset's relevance to the leaderboard results.

Your response will greatly assist me.

Thank you for your attention to this matter.

**Comment by penghao-wu** [comment]
Yes, we use the provided dataset for the leaderboard submission.
