### ISSUE TITLE
error

### ISSUE THREAD

**Issue by a1wj1** [OpenDriveLab/TCP#56]
Hello, may I ask if there is an error in the code in tools/gen_ In data.py, there are：          
```
full_seq_x.append(measurement['y'])
full_seq_y.append(measurement['x'])

```
The correct one should be the following：
```
full_seq_x.append(measurement['x'])
full_seq_y.append(measurement['y'])
```

right?

**Comment by penghao-wu** [comment]
We convert the coordinate here. It is not an error, sorry for the confusion.
