### ISSUE TITLE
Could you please provide the script to generate town06_addition?

### ISSUE THREAD

**Issue by xanhug** [OpenDriveLab/TCP#57]
Thanks for your amazing work!
when I try to generate dataset, I found there is no script of town06_addition compared to your provided dataset.
could you please provide the script to generate town06_addition?
![截图 2023-11-01 17-55-31](https://github.com/OpenDriveLab/TCP/assets/109917206/685548a9-428f-4c38-8221-7cd3b386e45c)
![截图 2023-11-01 17-54-59](https://github.com/OpenDriveLab/TCP/assets/109917206/23db2f74-cec4-424f-b478-1564ec2841b2)

**Comment by penghao-wu** [comment]
Hi, I have uploaded the missing xml file. Thank you for pointing this out. And we use tools/generate_random_routes.py to generate these routes.

**Comment by xanhug** [comment]
> Hi, I have uploaded the missing xml file. Thank you for pointing this out. And we use tools/generate_random_routes.py to generate these routes.

Thank you so much!
