### ISSUE TITLE
Question about speed / 12.

### ISSUE THREAD

**Issue by xanhug** [OpenDriveLab/TCP#59]
When learning your code, there's a point that confuses me. Why is the 'speed' divided by 12 in this section?
https://github.com/OpenDriveLab/TCP/blob/779f193efdf751c12dbb9e71998800098ef3860e/TCP/train.py#L50

**Comment by penghao-wu** [comment]
We normalize the speed input to 0 to 1.

**Comment by xanhug** [comment]
> We normalize the speed input to 0 to 1.

Thanks for your reply.
