### ISSUE TITLE
The question about setting TEAM_CONFIG path in Evaluation

### ISSUE THREAD

**Issue by ml6362662** [OpenDriveLab/TCP#62]
Hello, I'm a beginner carla autopilot student, mentioned in the Evaluation section of your README.md file, you need to manually set the path of model ckpt at the TEAM_CONFIG in the leaderboard/scripts/run_evaluation.sh file, but I don't know which model ckpt is this model configuration file, or how to get model ckpt. I would like to ask you about this TEAM_ How CONFIG should be set up, thank you very much.
![微信图片_20240524172804](https://github.com/OpenDriveLab/TCP/assets/130368193/29e0fc67-8908-469f-97be-1cb562addd72)
![微信图片_20240524173007](https://github.com/OpenDriveLab/TCP/assets/130368193/3834e4a4-1a21-41cb-ae4f-c8599df88b4c)

**Comment by HXTYI** [comment]
Have you solved this problem? I have encountered this too.

**Comment by zdy1013** [comment]
This is the path to the ckpt file you trained yourself to get.

**Comment by 1585596474** [comment]
> This is the path to the ckpt file you trained yourself to get.

Hi, I trained the network, but I don't know the directory of the ckpt file. Can you tell me the default directory?
