### ISSUE TITLE
Question about Carla simulator time delta settings

### ISSUE THREAD

**Issue by dragnil1** [OpenDriveLab/TCP#64]
In the original roach codebase the time delta of Carla simulator is 0.1 seconds. But in your implementation you used 0.05 seconds. Will it it create any issue while data collection using the roach agent as the agent is trained in 0.1 seconds time delta. The agent perception is different when time delta is different.

**Comment by penghao-wu** [comment]
Hi, we will only update the roach agent every 2 steps (https://github.com/OpenDriveLab/TCP/blob/9ec4db0f0424801cdd607f1de930290830c5e88e/leaderboard/team_code/roach_ap_agent.py#L319).
