### ISSUE TITLE
Reproducing the results of the questioning

### ISSUE THREAD

**Issue by zdy1013** [OpenDriveLab/TCP#67]
I'm glad you published such a great work, why are the results I get so different from yours when I use 2 RTX 3090s and train with 60 epochs using the dataset you provided and evaluate it? Here are the results I reproduced:
Avg. driving score: 52.005
Avg. route completion: 85.111
Avg. infraction penalty: 0.647
Collisions with pedestrians: 0.000
Collisions with vehicles: 0.270
Collisions with layout: 0.097
Red lights infractions: 0.070
Stop sign infractions: 0.238
Off-road infractions: 0.198
Route deviations: 0.000
Route timeouts: 0.094
Agent blocked: 0.298

**Comment by penghao-wu** [comment]
> I'm glad you published such a great work, why are the results I get so different from yours when I use 2 RTX 3090s and train with 60 epochs using the dataset you provided and evaluate it? Here are the results I reproduced: Avg. driving score: 52.005 Avg. route completion: 85.111 Avg. infraction penalty: 0.647 Collisions with pedestrians: 0.000 Collisions with vehicles: 0.270 Collisions with layout: 0.097 Red lights infractions: 0.070 Stop sign infractions: 0.238 Off-road infractions: 0.198 Route deviations: 0.000 Route timeouts: 0.094 Agent blocked: 0.298

I suppose you are evaluating the model in 48 routes where our model has 57.01 driving score as reported in the paper. I think the difference is reasonable considering the variance in evaluation and training.

**Comment by zdy1013** [comment]
> > I'm glad you published such a great work, why are the results I get so different from yours when I use 2 RTX 3090s and train with 60 epochs using the dataset you provided and evaluate it? Here are the results I reproduced: Avg. driving score: 52.005 Avg. route completion: 85.111 Avg. infraction penalty: 0.647 Collisions with pedestrians: 0.000 Collisions with vehicles: 0.270 Collisions with layout: 0.097 Red lights infractions: 0.070 Stop sign infractions: 0.238 Off-road infractions: 0.198 Route deviations: 0.000 Route timeouts: 0.094 Agent blocked: 0.298
> 
> I suppose you are evaluating the model in 48 routes where our model has 57.01 driving score as reported in the paper. I think the difference is reasonable considering the variance in evaluation and training.

Thank you for your reply. May I ask how to operate if I want to reproduce your score of 75.14?
![Screenshot_2024-08-06-16-12-15-62_df198e732186825c8df26e3c5a10d7cd](https://github.com/user-attachments/assets/f0137c59-1cc7-4b4f-b76f-99b2c0902483)

**Comment by penghao-wu** [comment]
We use all 420K data for training. And the ensemble of the TCP and TCP-SB models is used. Some details can be found in the paper.
![image](https://github.com/user-attachments/assets/e1cc0ddc-1f18-40a9-8fb5-d6456416018a)

**Comment by zdy1013** [comment]
> We use all 420K data for training. And the ensemble of the TCP and TCP-SB models is used. Some details can be found in the paper. ![image](https://private-user-images.githubusercontent.com/62696862/355370739-e1cc0ddc-1f18-40a9-8fb5-d6456416018a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzQyOTAsIm5iZiI6MTcyMjkzMzk5MCwicGF0aCI6Ii82MjY5Njg2Mi8zNTUzNzA3MzktZTFjYzBkZGMtMWYxOC00MGE5LThmYjUtZDY0NTY0MTYwMThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA4NDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NDA1OWIxNThlYTAyZTQyMmZiZWYzNjQxNzdiNWY2MjViNDVlMjllOWJmMTExNDZiYTI0ZDQxOTJmNTc1MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HjAHkFQaesC2DYoq2TB_9d7ICt556Z2zFV6NcGEaGA0)

I would like to know, how do you integrate?What's more, is the data set you provided for 4 towns?

**Comment by penghao-wu** [comment]
The dataset file should contain all 8 towns' data. For the ensemble strategy, please refer to the last sentence in the image.

**Comment by HXTYI** [comment]
Hello author, I recently reproduced this project, but the test score is similar to the above figure, between 50-60. What do you mean by 420K data? Is this 115G tcp_carla_data?
If I want the results in the figure, do I also need to "If it is a trajectory specialization case, we set α=0.5, if it is a control specialization case, we take the maximum value of the brake control instead of the average value"
Hope u can reply !

**Comment by HXTYI** [comment]
@penghao-wu 
Hello author, I recently reproduced this project, but the test score is similar to the above figure, between 50-60. What do you mean by 420K data? Is this 115G tcp_carla_data?
If I want the results in the figure, do I also need to "If it is a trajectory specialization case, we set α=0.5, if it is a control specialization case, we take the maximum value of the brake control instead of the average value"
Hope u can reply !

**Comment by penghao-wu** [comment]
> @penghao-wu Hello author, I recently reproduced this project, but the test score is similar to the above figure, between 50-60. What do you mean by 420K data? Is this 115G tcp_carla_data? If I want the results in the figure, do I also need to "If it is a trajectory specialization case, we set α=0.5, if it is a control specialization case, we take the maximum value of the brake control instead of the average value" Hope u can reply !

Yes, the 420K data includes all 8 towns' data in the data zip.
Yes.

**Comment by Mr-ChenSH** [comment]
@penghao-wu  OK，I konw it.
