### ISSUE TITLE
    from agents.navigation.global_route_planner import GlobalRoutePlanner ModuleNotFoundError: No module named 'agents.navigation'

### ISSUE THREAD

**Issue by Mr-ChenSH** [OpenDriveLab/TCP#68]
run  sh leaderboard/scripts/data_collection.sh encounter this problem

**Comment by penghao-wu** [comment]
Could you please modify the issue title to make it concise? For you problem, please make sure you set this correctly https://github.com/OpenDriveLab/TCP/blob/9ec4db0f0424801cdd607f1de930290830c5e88e/leaderboard/scripts/data_collection.sh#L2.

**Comment by Mr-ChenSH** [comment]
Traceback (most recent call last):
  File "/home/cybersec/TCP-main/leaderboard/leaderboard/leaderboard_evaluator.py", line 34, in <module>
    from leaderboard.scenarios.scenario_manager import ScenarioManager
  File "/home/cybersec/TCP-main/leaderboard/leaderboard/scenarios/scenario_manager.py", line 25, in <module>
    from leaderboard.autoagents.agent_wrapper import AgentWrapper, AgentError
  File "/home/cybersec/TCP-main/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 21, in <module>
    from leaderboard.autoagents.autonomous_agent import Track
  File "/home/cybersec/TCP-main/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 17, in <module>
    from leaderboard.utils.route_manipulation import downsample_route
  File "/home/cybersec/TCP-main/leaderboard/leaderboard/utils/route_manipulation.py", line 22, in <module>
    from agents.navigation.global_route_planner import GlobalRoutePlanner
ModuleNotFoundError: No module named 'agents.navigation'

**Comment by Mr-ChenSH** [comment]
export CARLA_ROOT=/home/cybersec/Work/Docker/carla/share/PythonAPI/carla
Even after adding it, there is still an error message

**Comment by penghao-wu** [comment]
The structure of your carla directory looks a bit weird. Why is there a `share` directory? I think in your case, you need to set `CARLA_ROOT` to /home/cybersec/Work/Docker/carla/share

**Comment by Mr-ChenSH** [comment]
sorry, I have already resolved this error

**Comment by Mr-ChenSH** [comment]
Traceback (most recent call last):
  File "/home/cybersec/TCP-main/leaderboard/leaderboard/leaderboard_evaluator.py", line 350, in _load_and_run_scenario
    self._load_and_wait_for_world(args, config.town, config.ego_vehicles)
  File "/home/cybersec/TCP-main/leaderboard/leaderboard/leaderboard_evaluator.py", line 232, in _load_and_wait_for_world
    self.traffic_manager.set_synchronous_mode(False)
AttributeError: 'LeaderboardEvaluator' object has no attribute 'traffic_manager'
> Registering the route statistics
But another new error has occurred

**Comment by Mr-ChenSH** [comment]
But another new error has occurred

**Comment by penghao-wu** [comment]
Please check whether `traffic_manager` is successfully set here https://github.com/OpenDriveLab/TCP/blob/9ec4db0f0424801cdd607f1de930290830c5e88e/leaderboard/leaderboard/leaderboard_evaluator.py#L111

**Comment by Mr-ChenSH** [comment]
![8PIQVBV~M0$97ZSWK{UM0P7](https://github.com/user-attachments/assets/63e83f48-f0cb-4915-acb7-1415e8f7c837)

**Comment by Mr-ChenSH** [comment]
It's here, I haven't made any changes

**Comment by penghao-wu** [comment]
I mean you can debug a little bit here to see whether it is successfully setup here in your case or it goes to the `except` branch.

**Comment by Mr-ChenSH** [comment]
Can I run eval directly after running the train

**Comment by Mr-ChenSH** [comment]
I encountered this issue while running eval
![image](https://github.com/user-attachments/assets/0bd93ef0-ced9-4ff4-a8e8-eed7fedd6682)

**Comment by penghao-wu** [comment]
Have you modified the code? The line 5 in `TCP/model.py` should be https://github.com/OpenDriveLab/TCP/blob/9ec4db0f0424801cdd607f1de930290830c5e88e/TCP/model.py#L5

**Comment by Mr-ChenSH** [comment]
yes，I modified it

**Comment by Mr-ChenSH** [comment]
The current mistake is as follows：
![d1e69ec3ac0aaa3ea228407c8195ad8](https://github.com/user-attachments/assets/89fddaf4-2fbf-47de-bb25-2739eb084be9)

**Comment by penghao-wu** [comment]
Please first try the original code without your modifications to see whether it works.

**Comment by penghao-wu** [comment]
I think it is related to your network issue.

**Comment by Mr-ChenSH** [comment]
![image](https://github.com/user-attachments/assets/a45d7a9e-871a-42ae-8e11-0712a9ea7d01)
I downloaded it online, but now I'm encountering this issue. Do I need to include the dataset in the project during verification

**Comment by Mr-ChenSH** [comment]
There is no dataset in this project

**Comment by penghao-wu** [comment]
You don't need dataset for evaluation. Make sure you strictly follow the readme for the installation of carla and this repo.

**Comment by Mr-ChenSH** [comment]
I have completed it, thank you very much！
